import type { ReportHistoryItem } from '../../types';

interface ViewReportModalProps {
  show: boolean;
  report: ReportHistoryItem | null;
  onClose: () => void;
}

export const ViewReportModal = ({ show, report, onClose }: ViewReportModalProps) => {
  if (!show || !report) return null;

  return (
    <div className="modal-backdrop-custom" onClick={onClose}>
      <div
        className="modal-dialog-custom"
        onClick={(e) => e.stopPropagation()}
        style={{
          animation: 'modalSlideIn 0.3s ease-out',
        }}
      >
        <div className="modal-content-custom">
          {/* Header */}
          <div className="d-flex align-items-center justify-content-between p-3 border-bottom">
            <h5 className="mb-0 fw-bold">
              <i className="bi bi-eye me-2" />
              Report Details
            </h5>
            <button className="btn btn-sm btn-outline-secondary border-0" onClick={onClose}>
              <i className="bi bi-x-lg" />
            </button>
          </div>

          {/* Body */}
          <div className="p-3">
            <div className="d-flex flex-column gap-3">
              {/* Report Name */}
              <div className="d-flex justify-content-between align-items-center p-3 rounded" style={{ background: 'var(--admin-surface-soft)' }}>
                <span className="small fw-semibold text-muted">Report Name</span>
                <span className="fw-bold">{report.reportName}</span>
              </div>

              {/* Report Type */}
              <div className="d-flex justify-content-between align-items-center p-3 rounded" style={{ background: 'var(--admin-surface-soft)' }}>
                <span className="small fw-semibold text-muted">Report Type</span>
                <span className="badge text-bg-primary">{report.reportType}</span>
              </div>

              {/* Project */}
              <div className="d-flex justify-content-between align-items-center p-3 rounded" style={{ background: 'var(--admin-surface-soft)' }}>
                <span className="small fw-semibold text-muted">Project</span>
                <span className="fw-semibold">{report.project}</span>
              </div>

              {/* Site */}
              <div className="d-flex justify-content-between align-items-center p-3 rounded" style={{ background: 'var(--admin-surface-soft)' }}>
                <span className="small fw-semibold text-muted">Site</span>
                <span className="fw-semibold">{report.site}</span>
              </div>

              {/* Chainage */}
              <div className="d-flex justify-content-between align-items-center p-3 rounded" style={{ background: 'var(--admin-surface-soft)' }}>
                <span className="small fw-semibold text-muted">Chainage</span>
                <span className="fw-semibold">{report.chainage}</span>
              </div>

              {/* Generated By */}
              <div className="d-flex justify-content-between align-items-center p-3 rounded" style={{ background: 'var(--admin-surface-soft)' }}>
                <span className="small fw-semibold text-muted">Generated By</span>
                <span className="fw-semibold">{report.generatedBy}</span>
              </div>

              {/* Generated Date */}
              <div className="d-flex justify-content-between align-items-center p-3 rounded" style={{ background: 'var(--admin-surface-soft)' }}>
                <span className="small fw-semibold text-muted">Generated Date</span>
                <span className="fw-semibold">{report.generatedDate}</span>
              </div>

              {/* Status */}
              <div className="d-flex justify-content-between align-items-center p-3 rounded" style={{ background: 'var(--admin-surface-soft)' }}>
                <span className="small fw-semibold text-muted">Status</span>
                <span className={`badge ${report.status === 'Ready' ? 'text-bg-success' : report.status === 'Generating' ? 'text-bg-warning' : 'text-bg-danger'}`}>
                  {report.status === 'Ready' && '🟢 '}
                  {report.status === 'Generating' && '🟡 '}
                  {report.status === 'Failed' && '🔴 '}
                  {report.status}
                </span>
              </div>

              {/* Format */}
              <div className="d-flex justify-content-between align-items-center p-3 rounded" style={{ background: 'var(--admin-surface-soft)' }}>
                <span className="small fw-semibold text-muted">Format</span>
                <span className={`badge ${report.format === 'PDF' ? 'text-bg-danger' : 'text-bg-info'}`}>
                  {report.format === 'PDF' ? '🟥' : '🟦'} {report.format}
                </span>
              </div>

              {/* Description */}
              <div className="p-3 rounded" style={{ background: 'var(--admin-surface-soft)' }}>
                <span className="small fw-semibold text-muted d-block mb-2">Description</span>
                <p className="mb-0 small">
                  This is a preview of the {report.reportType} generated for {report.site} ({report.chainage}) on {report.generatedDate}. 
                  The report was generated by {report.generatedBy} in {report.format} format.
                </p>
              </div>
            </div>
          </div>

          {/* Footer */}
          <div className="d-flex justify-content-end p-3 border-top">
            <button className="btn btn-outline-secondary" onClick={onClose}>
              Close
            </button>
          </div>
        </div>

        <style>{`
          @keyframes modalSlideIn {
            from {
              opacity: 0;
              transform: translateY(-20px) scale(0.95);
            }
            to {
              opacity: 1;
              transform: translateY(0) scale(1);
            }
          }
          .modal-backdrop-custom {
            position: fixed;
            inset: 0;
            z-index: 1055;
            display: flex;
            align-items: center;
            justify-content: center;
            background: rgba(15, 23, 42, 0.6);
            backdrop-filter: blur(4px);
            padding: 1rem;
          }
          .modal-dialog-custom {
            width: 100%;
            max-width: 520px;
            max-height: 90vh;
            background: #fff;
            border-radius: 12px;
            box-shadow: 0 25px 60px rgba(15, 23, 42, 0.25);
            overflow: hidden;
          }
          .modal-content-custom {
            display: flex;
            flex-direction: column;
          }
        `}</style>
      </div>
    </div>
  );
};