import api from './api';
import type { Report } from '../types';

export const generateCSVBlob = (report: Partial<Report>): Blob => {
  const headers = ['ID', 'Title', 'Report Type', 'Format', 'Generated By', 'Generated Date', 'Status'];
  const row = [
    `"${report.id || Date.now()}"`,
    `"${report.title || 'L&T AMS Report'}"`,
    `"${report.type || 'General'}"`,
    `"${report.format || 'csv'}"`,
    `"${report.generatedBy || 'System'}"`,
    `"${report.generatedAt || new Date().toISOString()}"`,
    `"${report.status || 'ready'}"`
  ];
  const csvContent = `${headers.join(',')}\n${row.join(',')}\n`;
  return new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
};

export const generatePDFBlob = (report: Partial<Report>): Blob => {
  const title = report.title || 'L&T Construction - Site Performance & Compliance Report';
  const typeStr = report.type || 'Daily Safety';
  const pdfText = `%PDF-1.4
1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj
2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj
3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >> endobj
5 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj
4 0 obj << /Length 300 >> stream
BT
/F1 18 Tf
50 720 TD
(${title.replace(/[()]/g, '')}) Tj
/F1 12 Tf
0 -30 TD
(L&T Construction & Infrastructure Analytics Platform) Tj
0 -20 TD
(Report Type: ${typeStr} | Format: PDF) Tj
0 -20 TD
(Generated By: ${report.generatedBy || 'Admin'} | Date: ${new Date().toLocaleDateString()}) Tj
0 -30 TD
(Status: ${report.status || 'Ready'}) Tj
ET
endstream
endobj
xref
0 6
0000000000 65535 f 
0000000009 00000 n 
0000000058 00000 n 
0000000115 00000 n 
0000000262 00000 n 
0000000610 00000 n 
trailer << /Size 6 /Root 1 0 R >>
startxref
680
%%EOF`;
  return new Blob([pdfText], { type: 'application/pdf' });
};

export const triggerBrowserDownload = (blob: Blob, filename: string) => {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

export const reportService = {
  async getReports(params?: Record<string, unknown>): Promise<Report[]> {
    const response = await api.get('reports/', { params });
    const data = response.data?.data || response.data;
    return Array.isArray(data) ? data : data?.results || [];
  },

  async generateReport(params: { type: string; dateRange: { start: string; end: string }; format: string; siteId?: string; projectId?: string }): Promise<Report> {
    const response = await api.post('reports/generate/', params);
    return response.data?.data || response.data;
  },

  async downloadReport(id: string): Promise<Blob> {
    try {
      const response = await api.get(`reports/${id}/download/`, { responseType: 'blob' });
      return response.data;
    } catch {
      // Fallback local Blob generator
      return generatePDFBlob({ id, title: `Report_${id}` });
    }
  },
};

export default reportService;
