import { useState, useMemo } from 'react';
import type { Column } from '../components/tables/ReusableDataTable';
import { GenerateReportModal } from '../components/reports/GenerateReportModal';
import { ViewReportModal } from '../components/reports/ViewReportModal';
import { INITIAL_REPORT_HISTORY, MOCK_SITES_LIST, MOCK_PROJECTS_LIST, MOCK_CHAINAGES_LIST } from '../services/mockData';
import type { ReportHistoryItem, ReportFileFormat } from '../types';

// ── Statistics card config ────────────────────────────────────────────────
const STAT_CARDS = [
  { key: 'all', label: 'All Reports', icon: 'bi-files', color: '#0d6efd' },
  { key: 'ready', label: 'Ready', icon: 'bi-check-circle-fill', color: '#198754' },
  { key: 'generating', label: 'Generating', icon: 'bi-hourglass-split', color: '#ffc107' },
  { key: 'pdf', label: 'PDF Format', icon: 'bi-file-pdf-fill', color: '#dc3545' },
  { key: 'csv', label: 'CSV Format', icon: 'bi-file-earmark-spreadsheet', color: '#0dcaf0' },
] as const;

// ── Helper: download a blob as a file ─────────────────────────────────────
function downloadBlob(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function downloadReport(item: ReportHistoryItem) {
  const isPdf = item.format === 'PDF';
  const filename = `${item.reportName.replace(/\s+/g, '_')}.${isPdf ? 'pdf' : 'csv'}`;
  const content = isPdf
    ? `Mock PDF Report: ${item.reportName}\nType: ${item.reportType}\nSite: ${item.site}\nChainage: ${item.chainage}\nGenerated By: ${item.generatedBy}\nDate: ${item.generatedDate}`
    : `Report Name,Report Type,Site,Chainage,Generated By,Date\n${item.reportName},${item.reportType},${item.site},${item.chainage},${item.generatedBy},${item.generatedDate}`;
  const mimeType = isPdf ? 'application/pdf' : 'text/csv';
  downloadBlob(content, filename, mimeType);
}

// ── Status badge helper ───────────────────────────────────────────────────
function StatusBadge({ status }: { status: ReportHistoryItem['status'] }) {
  const map: Record<string, { bg: string; icon: string }> = {
    Ready: { bg: 'text-bg-success', icon: '🟢' },
    Generating: { bg: 'text-bg-warning', icon: '🟡' },
    Failed: { bg: 'text-bg-danger', icon: '🔴' },
  };
  const c = map[status] ?? { bg: 'text-bg-secondary', icon: '⚪' };
  return (
    <span className={`badge ${c.bg}`}>
      {c.icon} {status}
    </span>
  );
}

// ── Format badge helper ───────────────────────────────────────────────────
function FormatBadge({ format }: { format: ReportFileFormat }) {
  return (
    <span className={`badge ${format === 'PDF' ? 'text-bg-danger' : 'text-bg-info'} me-1`}>
      {format === 'PDF' ? '🟥' : '🟦'} {format}
    </span>
  );
}

// ── Column definitions ────────────────────────────────────────────────────
const COLUMNS: Column<ReportHistoryItem>[] = [
  {
    key: 'reportName',
    header: 'Report Name',
    render: (r) => (
      <div>
        <p className="fw-semibold mb-0 text-truncate" style={{ maxWidth: '180px' }}>{r.reportName}</p>
        <small className="text-muted">{r.reportType}</small>
      </div>
    ),
  },
  { key: 'reportType', header: 'Report Type' },
  { key: 'site', header: 'Site' },
  { key: 'chainage', header: 'Chainage' },
  { key: 'generatedBy', header: 'Generated By' },
  { key: 'generatedDate', header: 'Generated On' },
  {
    key: 'status',
    header: 'Status',
    render: (r) => <StatusBadge status={r.status} />,
  },
  {
    key: 'actions',
    header: 'Action',
    className: 'text-end',
    render: (r) => (
      <div className="d-flex gap-1 justify-content-end flex-nowrap">
        <FormatBadge format={r.format} />
        {r.status === 'Ready' && (
          <button
            className="btn btn-sm btn-outline-primary"
            title="Download"
            onClick={() => downloadReport(r)}
          >
            <i className="bi bi-download" />
          </button>
        )}
        <button
          className="btn btn-sm btn-outline-secondary"
          title="View"
          onClick={() => {/* View handled by parent */ }}
        >
          <i className="bi bi-eye" />
        </button>
      </div>
    ),
  },
];

// ── Main Page Component ───────────────────────────────────────────────────
export const ReportsPage = () => {
  // Report history state
  const [reports, setReports] = useState<ReportHistoryItem[]>(INITIAL_REPORT_HISTORY);

  // Search & filter state
  const [search, setSearch] = useState('');
  const [filter, setFilter] = useState<string>('all');
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(5);

  // Advanced filter state
  const [filterProject, setFilterProject] = useState('');
  const [filterSite, setFilterSite] = useState('');
  const [filterChainage, setFilterChainage] = useState('');
  const [appliedProject, setAppliedProject] = useState('');
  const [appliedSite, setAppliedSite] = useState('');
  const [appliedChainage, setAppliedChainage] = useState('');

  // Modal state
  const [showGenerateModal, setShowGenerateModal] = useState(false);
  const [viewReport, setViewReport] = useState<ReportHistoryItem | null>(null);

  // View report handler
  const [showViewModal, setShowViewModal] = useState(false);

  const handleView = (report: ReportHistoryItem) => {
    setViewReport(report);
    setShowViewModal(true);
  };

  // Compute stats
  const stats = useMemo(() => {
    const all = reports.length;
    const ready = reports.filter((r) => r.status === 'Ready').length;
    const generating = reports.filter((r) => r.status === 'Generating').length;
    const pdf = reports.filter((r) => r.format === 'PDF').length;
    const csv = reports.filter((r) => r.format === 'CSV').length;
    return { all, ready, generating, pdf, csv };
  }, [reports]);

  // Filter logic
  const filtered = useMemo(() => {
    return reports.filter((r) => {
      // Search
      if (search) {
        const q = search.toLowerCase();
        const matchSearch =
          r.reportName.toLowerCase().includes(q) ||
          r.site.toLowerCase().includes(q) ||
          r.reportType.toLowerCase().includes(q) ||
          r.generatedBy.toLowerCase().includes(q) ||
          r.format.toLowerCase().includes(q) ||
          r.status.toLowerCase().includes(q);
        if (!matchSearch) return false;
      }

      // Status/Format filter
      if (filter === 'ready' && r.status !== 'Ready') return false;
      if (filter === 'generating' && r.status !== 'Generating') return false;
      if (filter === 'pdf' && r.format !== 'PDF') return false;
      if (filter === 'csv' && r.format !== 'CSV') return false;

      // Applied filters
      if (appliedProject && r.project !== appliedProject) return false;
      if (appliedSite && r.site !== appliedSite) return false;
      if (appliedChainage && r.chainage !== appliedChainage) return false;

      return true;
    });
  }, [reports, search, filter, appliedProject, appliedSite, appliedChainage]);

  const sliced = filtered.slice((page - 1) * pageSize, page * pageSize);

  const handleGenerate = (newReport: ReportHistoryItem) => {
    setReports((prev) => [newReport, ...prev]);
  };

  // Inject view handler into columns
  const columnsWithView: Column<ReportHistoryItem>[] = COLUMNS.map((col) => {
    if (col.key === 'actions') {
      return {
        ...col,
        render: (r: ReportHistoryItem) => (
          <div className="d-flex gap-1 justify-content-end flex-nowrap">
            <FormatBadge format={r.format} />
            {r.status === 'Ready' && (
              <button
                className="btn btn-sm btn-outline-primary"
                title="Download"
                onClick={() => downloadReport(r)}
              >
                <i className="bi bi-download" />
              </button>
            )}
            <button
              className="btn btn-sm btn-outline-secondary"
              title="View"
              onClick={() => handleView(r)}
            >
              <i className="bi bi-eye" />
            </button>
          </div>
        ),
      };
    }
    return col;
  });

  return (
    <div className="container-fluid px-3 px-lg-4 py-4">
      <div className="page-heading">
        <div className="page-heading-copy">
          <span className="page-icon"><i className="bi bi-file-earmark-bar-graph" aria-hidden="true" /></span>
          <div>
            <h1 className="h3 mb-0">Reports</h1>
          </div>
        </div>
        <div className="heading-actions">
          <button
            className="btn btn-primary btn-sm"
            onClick={() => setShowGenerateModal(true)}
          >
            <i className="bi bi-plus-lg" /> Generate Report
          </button>
        </div>
      </div>

      {/* ── Filters Bar ─────────────────────────────────────────────── */}
      <div className="card border-0 shadow-sm p-3 mb-4 bg-white">
        <div className="row g-2 align-items-center">
          <div className="col-auto">
            <span className="small text-muted fw-bold text-uppercase">Report Filters:</span>
          </div>

          <div className="col-sm-3 col-md-3 col-xl-2">
            <select
              className="form-select form-select-sm"
              value={filterProject}
              onChange={(e) => {
                setFilterProject(e.target.value);
                setFilterSite('');
                setFilterChainage('');
              }}
            >
              <option value="">All Projects</option>
              {MOCK_PROJECTS_LIST.map((p) => (
                <option key={p} value={p}>{p}</option>
              ))}
            </select>
          </div>

          <div className="col-sm-3 col-md-3 col-xl-2">
            <select
              className="form-select form-select-sm"
              value={filterSite}
              onChange={(e) => {
                setFilterSite(e.target.value);
                setFilterChainage('');
              }}
            >
              <option value="">All Sites</option>
              {MOCK_SITES_LIST.map((s) => (
                <option key={s} value={s}>{s}</option>
              ))}
            </select>
          </div>

          <div className="col-sm-3 col-md-3 col-xl-2">
            <select
              className="form-select form-select-sm"
              value={filterChainage}
              onChange={(e) => setFilterChainage(e.target.value)}
              disabled={!filterSite}
            >
              <option value="">All Chainages</option>
              {MOCK_CHAINAGES_LIST.map((c) => (
                <option key={c} value={c}>{c}</option>
              ))}
            </select>
          </div>

          <div className="col-auto ms-auto d-flex gap-2">
            <button
              className="btn btn-sm btn-primary px-3 fw-bold"
              onClick={() => {
                setAppliedProject(filterProject);
                setAppliedSite(filterSite);
                setAppliedChainage(filterChainage);
              }}
            >
              Apply Filter
            </button>
            <button
              className="btn btn-sm btn-outline-secondary px-3"
              onClick={() => {
                setFilterProject('');
                setFilterSite('');
                setFilterChainage('');
                setAppliedProject('');
                setAppliedSite('');
                setAppliedChainage('');
              }}
            >
              Reset
            </button>
          </div>
        </div>
      </div>

      {/* ── Statistics Cards ────────────────────────────────────────── */}
      <div className="row row-cols-2 row-cols-sm-3 row-cols-md-5 g-3 mt-1 mb-4">
        {STAT_CARDS.map((s) => {
          const count = stats[s.key as keyof typeof stats];
          const isActive = filter === s.key;

          return (
            <div key={s.key} className="col">
              <div
                className={`mini-card text-center p-2.5 h-100 d-flex flex-column align-items-center justify-content-center gap-1 border rounded ${isActive ? 'bg-primary-subtle border-primary text-primary' : 'bg-white border-light-subtle text-muted'
                  }`}
                style={{ cursor: 'pointer', transition: 'all 0.2s ease', minHeight: '85px' }}
                onClick={() => { setFilter(s.key); setPage(1); }}
              >
                <i className={`bi ${s.icon} fs-5`} style={{ color: isActive ? 'inherit' : s.color }} />
                <strong className="fs-5 lh-1 text-dark fw-bold">{count}</strong>
                <span className="small text-capitalize" style={{ fontSize: '11px', fontWeight: 500 }}>{s.label}</span>
              </div>
            </div>
          );
        })}
      </div>

      {/* ── Report Table ─────────────────────────────────────────────── */}
      <div className="panel p-0">
        {/* Search bar inside panel */}
        <div className="p-3 border-bottom">
          <div className="d-flex flex-wrap align-items-center gap-2">
            <div className="position-relative flex-grow-1" style={{ maxWidth: '360px' }}>
              <i className="bi bi-search position-absolute top-50 start-0 translate-middle-y ms-3 text-muted" />
              <input
                className="form-control form-control-sm ps-5"
                type="search"
                placeholder="Search by Report Name, Site, Type, Generated By, Format, Status..."
                value={search}
                onChange={(e) => { setSearch(e.target.value); setPage(1); }}
                aria-label="Search reports"
              />
            </div>
          </div>
        </div>

        <div className="table-responsive" style={{ maxHeight: '520px', overflowY: 'auto' }}>
          <table className="table align-middle mb-0" style={{ minWidth: '900px' }}>
            <thead className="sticky-top bg-white">
              <tr>
                {columnsWithView.map((col) => (
                  <th
                    key={col.key}
                    scope="col"
                    className={col.headerClassName}
                    style={{ width: col.width }}
                  >
                    {col.header}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {sliced.length === 0 ? (
                <tr>
                  <td colSpan={COLUMNS.length} className="text-center text-muted py-5">
                    <i className="bi bi-inbox fs-3 d-block mb-2" />
                    No reports found
                  </td>
                </tr>
              ) : (
                sliced.map((item) => (
                  <tr key={item.id} style={{ transition: 'background 0.16s ease' }}>
                    {columnsWithView.map((col) => (
                      <td key={col.key} className={col.className}>
                    {col.render ? col.render(item) : String((item as unknown as Record<string, unknown>)[col.key] ?? '')}
                      </td>
                    ))}
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>

        {/* Pagination */}
        {filtered.length > pageSize && (
          <div className="d-flex flex-column flex-sm-row align-items-sm-center justify-content-between gap-3 p-3 border-top">
            <div className="d-flex align-items-center gap-2">
              <small className="text-muted">
                Showing {((page - 1) * pageSize) + 1} to {Math.min(page * pageSize, filtered.length)} of {filtered.length}
              </small>
              <select
                className="form-select form-select-sm"
                style={{ width: 'auto' }}
                value={pageSize}
                onChange={(e) => { setPageSize(Number(e.target.value)); setPage(1); }}
              >
                {[5, 10, 20, 50].map((s) => (
                  <option key={s} value={s}>{s} / page</option>
                ))}
              </select>
            </div>
            <nav aria-label="Table pagination">
              <ul className="pagination pagination-sm mb-0">
                <li className={`page-item ${page <= 1 ? 'disabled' : ''}`}>
                  <button className="page-link" onClick={() => setPage(page - 1)} disabled={page <= 1}>Previous</button>
                </li>
                {Array.from({ length: Math.ceil(filtered.length / pageSize) }, (_, i) => i + 1).map((p) => (
                  <li key={p} className={`page-item ${p === page ? 'active' : ''}`}>
                    <button className="page-link" onClick={() => setPage(p)}>{p}</button>
                  </li>
                ))}
                <li className={`page-item ${page >= Math.ceil(filtered.length / pageSize) ? 'disabled' : ''}`}>
                  <button className="page-link" onClick={() => setPage(page + 1)} disabled={page >= Math.ceil(filtered.length / pageSize)}>Next</button>
                </li>
              </ul>
            </nav>
          </div>
        )}
      </div>

      {/* ── Modals ──────────────────────────────────────────────────── */}
      <GenerateReportModal
        show={showGenerateModal}
        onClose={() => setShowGenerateModal(false)}
        onGenerate={handleGenerate}
      />

      <ViewReportModal
        show={showViewModal}
        report={viewReport}
        onClose={() => { setShowViewModal(false); setViewReport(null); }}
      />
    </div>
  );
};