import { useState } from 'react';
import { ReusableDataTable, type Column } from '../components/tables/ReusableDataTable';
import { MOCK_REPORTS } from '../services/mockData';
import type { Report } from '../types';

const columns: Column<Report>[] = [
  { key: 'title', header: 'Report', render: (r) => (
    <div>
      <p className="fw-semibold mb-0">{r.title}</p>
      <small className="text-muted">{r.description}</small>
    </div>
  )},
  { key: 'type', header: 'Type', render: (r) => <span className="badge text-bg-primary">{r.type.replace(/_/g, ' ')}</span> },
  { key: 'format', header: 'Format', render: (r) => <span className={`badge ${r.format === 'pdf' ? 'text-bg-danger' : r.format === 'excel' ? 'text-bg-success' : 'text-bg-info'}`}>{r.format}</span> },
  { key: 'generatedBy', header: 'Generated By' },
  { key: 'generatedAt', header: 'Date', render: (r) => new Date(r.generatedAt).toLocaleDateString() },
  { key: 'status', header: 'Status', render: (r) => (
    <span className={`badge ${r.status === 'ready' ? 'text-bg-success' : r.status === 'generating' ? 'text-bg-warning' : 'text-bg-danger'}`}>{r.status}</span>
  )},
  { key: 'actions', header: 'Action', className: 'text-end', render: (r) => (
    <div className="d-flex gap-1 justify-content-end">
      {r.status === 'ready' && <button className="btn btn-sm btn-outline-primary"><i className="bi bi-download" /></button>}
      <button className="btn btn-sm btn-outline-secondary"><i className="bi bi-eye" /></button>
    </div>
  )},
];

export const ReportsPage = () => {
  const [search, setSearch] = useState('');

  const filtered = MOCK_REPORTS.filter((r) =>
    !search || r.title.toLowerCase().includes(search.toLowerCase()) || r.generatedBy.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div className="container-fluid px-3 px-lg-4 py-4">
      <div className="page-heading">
        <div className="page-heading-copy">
          <span className="page-icon"><i className="bi bi-file-earmark-bar-graph" aria-hidden="true" /></span>
          <div>
            <p className="eyebrow mb-1">Analytics</p>
            <h1 className="h3 mb-0">Reports & Analytics</h1>
          </div>
        </div>
        <div className="heading-actions">
          <button className="btn btn-primary btn-sm"><i className="bi bi-plus-lg" /> Generate Report</button>
        </div>
      </div>

      <div className="row g-3 mb-3">
        <div className="col-6 col-sm-3">
          <div className="mini-card text-center p-3">
            <strong className="fs-4">{MOCK_REPORTS.filter((r) => r.status === 'ready').length}</strong>
            <span className="text-muted small">Ready</span>
          </div>
        </div>
        <div className="col-6 col-sm-3">
          <div className="mini-card text-center p-3">
            <strong className="fs-4">{MOCK_REPORTS.filter((r) => r.status === 'generating').length}</strong>
            <span className="text-muted small">Generating</span>
          </div>
        </div>
        <div className="col-6 col-sm-3">
          <div className="mini-card text-center p-3">
            <strong className="fs-4">{MOCK_REPORTS.filter((r) => r.format === 'pdf').length}</strong>
            <span className="text-muted small">PDF</span>
          </div>
        </div>
        <div className="col-6 col-sm-3">
          <div className="mini-card text-center p-3">
            <strong className="fs-4">{MOCK_REPORTS.filter((r) => r.format === 'excel').length}</strong>
            <span className="text-muted small">Excel</span>
          </div>
        </div>
      </div>

      <ReusableDataTable
        columns={columns}
        data={filtered}
        keyExtractor={(r) => r.id}
        searchQuery={search}
        onSearch={setSearch}
        searchPlaceholder="Search reports..."
        total={filtered.length}
      />
    </div>
  );
};