import { useState, useEffect } from 'react';
import { ReusableDataTable, type Column } from '../components/tables/ReusableDataTable';
import { reportService } from '../services/reportService';
import { projectService } from '../services/projectService';
import { siteService } from '../services/siteService';
import type { Report, Project, Site, Chainage } from '../types';

const columns: Column<Report>[] = [
  {
    key: 'title', header: 'Report', render: (r) => (
      <div>
        <p className="fw-semibold mb-0">{r.title}</p>
        <small className="text-muted">{r.description}</small>
      </div>
    )
  },
  { key: 'type', header: 'Type', render: (r) => <span className="badge text-bg-primary">{r.type.replace(/_/g, ' ')}</span> },
  { key: 'format', header: 'Format', render: (r) => <span className={`badge ${r.format === 'pdf' ? 'text-bg-danger' : r.format === 'excel' ? 'text-bg-success' : 'text-bg-info'}`}>{r.format}</span> },
  { key: 'generatedBy', header: 'Generated By' },
  { key: 'generatedAt', header: 'Date', render: (r) => new Date(r.generatedAt).toLocaleDateString() },
  {
    key: 'status', header: 'Status', render: (r) => (
      <span className={`badge ${r.status === 'ready' ? 'text-bg-success' : r.status === 'generating' ? 'text-bg-warning' : 'text-bg-danger'}`}>{r.status}</span>
    )
  },
  {
    key: 'actions', header: 'Action', className: 'text-end', render: (r) => (
      <div className="d-flex gap-1 justify-content-end">
        {r.status === 'ready' && <button className="btn btn-sm btn-outline-primary"><i className="bi bi-download" /></button>}
        <button className="btn btn-sm btn-outline-secondary"><i className="bi bi-eye" /></button>
      </div>
    )
  },
];

const STATUS_CONFIGS: Record<string, { icon: string; activeClass: string; color: string; label: string }> = {
  all: { icon: 'bi-files', activeClass: 'bg-primary-subtle border-primary text-primary', color: '#0d6efd', label: 'All Reports' },
  ready: { icon: 'bi-check-circle-fill', activeClass: 'bg-success-subtle border-success text-success', color: '#198754', label: 'Ready' },
  generating: { icon: 'bi-hourglass-split', activeClass: 'bg-warning-subtle border-warning text-warning', color: '#ffc107', label: 'Generating' },
  pdf: { icon: 'bi-file-pdf-fill', activeClass: 'bg-danger-subtle border-danger text-danger', color: '#dc3545', label: 'PDF Format' },
  excel: { icon: 'bi-file-earmark-excel-fill', activeClass: 'bg-info-subtle border-info text-info', color: '#0dcaf0', label: 'Excel Format' },
};

export const ReportsPage = () => {
  const [reports, setReports] = useState<Report[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [filter, setFilter] = useState<string>('all');
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(5);

  // Dynamic DB data state
  const [dbProjects, setDbProjects] = useState<Project[]>([]);
  const [dbSites, setDbSites] = useState<Site[]>([]);
  const [dbChainages, setDbChainages] = useState<Chainage[]>([]);

  // Filters dropdown state
  const [filterProject, setFilterProject] = useState('');
  const [filterSite, setFilterSite] = useState('');
  const [filterChainage, setFilterChainage] = useState('');

  // Applied filter state
  const [appliedProject, setAppliedProject] = useState('');
  const [appliedSite, setAppliedSite] = useState('');
  const [appliedChainage, setAppliedChainage] = useState('');

  useEffect(() => {
    let isMounted = true;
    Promise.all([
      reportService.getReports().catch(() => []),
      projectService.getProjects().catch(() => []),
      siteService.getSites().catch(() => []),
      siteService.getChainages().catch(() => []),
    ]).then(([reportsData, projectsData, sitesData, chainagesData]) => {
      if (!isMounted) return;
      if (Array.isArray(reportsData)) setReports(reportsData);
      if (Array.isArray(projectsData)) setDbProjects(projectsData);
      if (Array.isArray(sitesData)) setDbSites(sitesData);
      if (Array.isArray(chainagesData)) setDbChainages(chainagesData);
    }).finally(() => {
      if (isMounted) setLoading(false);
    });
    return () => { isMounted = false; };
  }, []);

  const availableSites = filterProject
    ? dbSites.filter((s) => String(s.projectId || '') === String(filterProject))
    : dbSites;

  const availableChainages = filterSite
    ? dbChainages.filter((c) => String(c.siteId || '') === String(filterSite))
    : dbChainages;

  const filtered = reports.filter((r) => {
    if (search && !r.title.toLowerCase().includes(search.toLowerCase()) && !r.generatedBy.toLowerCase().includes(search.toLowerCase())) return false;
    if (filter === 'ready' && r.status !== 'ready') return false;
    if (filter === 'generating' && r.status !== 'generating') return false;
    if (filter === 'pdf' && r.format !== 'pdf') return false;
    if (filter === 'excel' && r.format !== 'excel') return false;

    if (appliedProject && r.projectId && String(r.projectId) !== String(appliedProject)) return false;
    if (appliedSite && r.siteId && String(r.siteId) !== String(appliedSite)) return false;
    if (appliedChainage && r.chainageId && String(r.chainageId) !== String(appliedChainage)) return false;

    return true;
  });

  const sliced = filtered.slice((page - 1) * pageSize, page * pageSize);

  return (
    <div className="container-fluid px-3 px-lg-4 py-4">
      <div className="page-heading">
        <div className="page-heading-copy">
          <span className="page-icon"><i className="bi bi-file-earmark-bar-graph" aria-hidden="true" /></span>
          <div>
            <h1 className="h3 mb-0">Reports</h1>
          </div>
        </div>
        <div className="heading-actions">
          <button className="btn btn-primary btn-sm"><i className="bi bi-plus-lg" /> Generate Report</button>
        </div>
      </div>

      {/* Filters Bar */}
      <div className="card border-0 shadow-sm p-3 mb-4 bg-white">
        <div className="row g-2 align-items-center">
          <div className="col-auto">
            <span className="small text-muted fw-bold text-uppercase">
              Report Filters:
            </span>
          </div>

          {/* Project dropdown */}
          <div className="col-sm-3 col-md-3 col-xl-2">
            <select
              className="form-select form-select-sm"
              value={filterProject}
              onChange={(e) => {
                setFilterProject(e.target.value);
                setFilterSite('');
                setFilterChainage('');
              }}
            >
              <option value="">All Projects</option>
              {dbProjects.map((p) => (
                <option key={p.id} value={p.id}>{p.name}</option>
              ))}
            </select>
          </div>

          {/* Site dropdown */}
          <div className="col-sm-3 col-md-3 col-xl-2">
            <select
              className="form-select form-select-sm"
              value={filterSite}
              onChange={(e) => {
                setFilterSite(e.target.value);
                setFilterChainage('');
              }}
            >
              <option value="">All Sites</option>
              {availableSites.map((s) => (
                <option key={s.id} value={s.id}>{s.name} ({s.code || s.location})</option>
              ))}
            </select>
          </div>

          {/* Chainage dropdown */}
          <div className="col-sm-3 col-md-3 col-xl-2">
            <select
              className="form-select form-select-sm"
              value={filterChainage}
              onChange={(e) => setFilterChainage(e.target.value)}
              disabled={!filterSite && availableChainages.length === 0}
            >
              <option value="">All Chainages</option>
              {availableChainages.map((c) => (
                <option key={c.id} value={c.id}>{c.name} {c.kmMarker ? `(${c.kmMarker})` : ''}</option>
              ))}
            </select>
          </div>

          {/* Action buttons */}
          <div className="col-auto ms-auto d-flex gap-2">
            <button
              className="btn btn-sm btn-primary px-3 fw-bold"
              onClick={() => {
                setAppliedProject(filterProject);
                setAppliedSite(filterSite);
                setAppliedChainage(filterChainage);
              }}
            >
              Apply Filter
            </button>
            <button
              className="btn btn-sm btn-outline-secondary px-3"
              onClick={() => {
                setFilterProject('');
                setFilterSite('');
                setFilterChainage('');
                setAppliedProject('');
                setAppliedSite('');
                setAppliedChainage('');
              }}
            >
              Reset
            </button>
          </div>
        </div>
      </div>

      {/* Summary cards */}
      <div className="row row-cols-2 row-cols-sm-3 row-cols-md-5 g-3 mt-1 mb-4">
        {['all', 'ready', 'generating', 'pdf', 'excel'].map((s) => {
          const config = STATUS_CONFIGS[s];
          const count = s === 'all'
            ? reports.length
            : (s === 'ready' || s === 'generating')
              ? reports.filter((r) => r.status === s).length
              : reports.filter((r) => r.format === s).length;

          const isActive = filter === s;

          return (
            <div key={s} className="col">
              <div
                className={`mini-card text-center p-2.5 h-100 d-flex flex-column align-items-center justify-content-center gap-1 border rounded ${isActive ? config.activeClass : 'bg-white border-light-subtle text-muted'
                  }`}
                style={{ cursor: 'pointer', transition: 'all 0.2s ease', minHeight: '85px' }}
                onClick={() => { setFilter(s); setPage(1); }}
              >
                <i className={`bi ${config.icon} fs-5`} style={{ color: isActive ? 'inherit' : config.color }} />
                <strong className="fs-5 lh-1 text-dark fw-bold">{count}</strong>
                <span className="small text-capitalize" style={{ fontSize: '11px', fontWeight: 500 }}>{config.label}</span>
              </div>
            </div>
          );
        })}
      </div>

      {loading ? (
        <div className="text-center py-5">
          <div className="spinner-border text-primary" role="status" />
          <p className="mt-2 text-muted">Loading reports...</p>
        </div>
      ) : (
        <ReusableDataTable
          columns={columns}
          data={sliced}
          keyExtractor={(r) => r.id}
          searchQuery={search}
          onSearch={(q) => { setSearch(q); setPage(1); }}
          searchPlaceholder="Search reports..."
          total={filtered.length}
          page={page}
          pageSize={pageSize}
          onPageChange={setPage}
          onPageSizeChange={setPageSize}
          showPagination={true}
        />
      )}
    </div>
  );
};